-- =========================================================================
-- GREEN_DATA DEMO DB SCHEMA (FULL 60 TABLES)
-- Совместимость: PostgreSQL 13+
-- Соответствует: data_generator_db.py (IdRegistry)
-- =========================================================================
BEGIN;

-- =========================================================================
-- LAYER 0: СПРАВОЧНИКИ БЕЗ FK
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.sys_state (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(2000) NOT NULL,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    type_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    org_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL DEFAULT 1,
    afr_ident VARCHAR(2000) NOT NULL DEFAULT 'STATE',
    afr_ord BIGINT NOT NULL DEFAULT 0,
    afr_note VARCHAR(2000),
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_system SMALLINT DEFAULT 0
);
COMMENT ON TABLE public.sys_state IS 'Состояние объекта';

CREATE TABLE IF NOT EXISTS public.sys_obj_type (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(2000) NOT NULL,
    ident VARCHAR(2000) NOT NULL,
    table_name VARCHAR(2000) NOT NULL,
    parent_id BIGINT,
    field_name_prefix VARCHAR(2000),
    is_hierarchy SMALLINT,
    is_system SMALLINT,
    type_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    status SMALLINT NOT NULL,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id BIGINT NOT NULL DEFAULT 1,
    name__en VARCHAR(2000),
    name__ru VARCHAR(2000),
    full_access_mask BIGINT NOT NULL DEFAULT 0,
    use_curmtx_rights SMALLINT,
    java_handler VARCHAR(2000),
    not_copy SMALLINT,
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    obj_type_attr_id BIGINT,
    is_time_depended SMALLINT,
    js_handler VARCHAR(2000),
    is_readonly_by_default SMALLINT,
    alg_saving_id BIGINT,
    alg_saved_id BIGINT,
    id_seq_name VARCHAR(2000),
    ext_types_multiselect SMALLINT,
    use_cache SMALLINT,
    hist_attr_force_create SMALLINT,
    link_access_attr_id BIGINT,
    access_type_id BIGINT,
    ext_types_widget_name VARCHAR(2000),
    ext_types_hide_btn SMALLINT,
    rf_connection BIGINT,
    attr_with_name BIGINT,
    alg_deleting_id BIGINT,
    display_obj_inst BIGINT,
    is_enabled_change_audit SMALLINT,
    allow_ignore_lifecycle SMALLINT,
    sys_content_type_id BIGINT,
    init_cache SMALLINT,
    sys_obj_type_is_mdata SMALLINT,
    note VARCHAR(2000),
    note__ru VARCHAR(2000),
    note__en VARCHAR(2000)
);
COMMENT ON TABLE public.sys_obj_type IS 'Тип объекта в Системе';

CREATE TABLE IF NOT EXISTS public.business_segment (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__en VARCHAR(2000),
    name__ru VARCHAR(2000),
    name VARCHAR(2000) NOT NULL,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    type_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    org_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ident VARCHAR(2000),
    type_int_code BIGINT
);
COMMENT ON TABLE public.business_segment IS 'Сегмент бизнеса клиента';

CREATE TABLE IF NOT EXISTS public.scp_techcred (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    ident VARCHAR(2000),
    name__en VARCHAR(2000)
);
COMMENT ON TABLE public.scp_techcred IS 'СКП. Технология кредитования';

CREATE TABLE IF NOT EXISTS public.scp_dict_tech_ctredit (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    ident VARCHAR(2000),
    type_int_code BIGINT,
    name__en VARCHAR(2000),
    is_available SMALLINT
);
COMMENT ON TABLE public.scp_dict_tech_ctredit IS 'СКП. Справочник: технология кредитования';

CREATE TABLE IF NOT EXISTS public.type_loan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    prod_type_upp_lev_id BIGINT,
    ord BIGINT,
    ident VARCHAR(2000),
    rel_submis_form SMALLINT,
    seq_prod_number BIGINT,
    name__en VARCHAR(2000)
);
COMMENT ON TABLE public.type_loan IS 'Справочник: вид кредита';

CREATE TABLE IF NOT EXISTS public.dict_div_presence (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT DEFAULT 0,
    nameregion VARCHAR(2000),
    coderegion VARCHAR(2000),
    div_presence SMALLINT DEFAULT 0,
    stop_region SMALLINT DEFAULT 0,
    stop_region_ko SMALLINT DEFAULT 0,
    stop_region_fact SMALLINT DEFAULT 0,
    name__en VARCHAR(2000)
);
COMMENT ON TABLE public.dict_div_presence IS 'Регионы присутствия';

CREATE TABLE IF NOT EXISTS public.cb_interest_rate (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    date_start_cb TIMESTAMP,
    date_end_cb TIMESTAMP,
    grade_number_cb NUMERIC
);
COMMENT ON TABLE public.cb_interest_rate IS 'Процентная ставка ЦБ';

CREATE TABLE IF NOT EXISTS public.tbs_type (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    identif VARCHAR(2000),
    acc_subconto_type_id BIGINT,
    name__en VARCHAR(2000)
);
COMMENT ON TABLE public.tbs_type IS 'Тип ОСВ';

CREATE TABLE IF NOT EXISTS public.acc_number (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    parent_acc BIGINT REFERENCES public.acc_number(id),
    account_name VARCHAR(2000),
    name__en VARCHAR(2000)
);
COMMENT ON TABLE public.acc_number IS 'ОСВ: Номер счета';

CREATE TABLE IF NOT EXISTS public.scp_gov_program_dict (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    ident VARCHAR(2000),
    scp_max_margin_val NUMERIC,
    scp_max_pref_rate_val NUMERIC,
    scp_subsidy_rate_val NUMERIC,
    type_gov_prog_id BIGINT,
    upp_gov_prog_dict_id BIGINT REFERENCES public.scp_gov_program_dict(id),
    date_end_cb TIMESTAMP,
    scp_fund_rate_val NUMERIC
);
COMMENT ON TABLE public.scp_gov_program_dict IS 'СКП. Госпрограмма';

CREATE TABLE IF NOT EXISTS public.scp_prod_guarant_dict (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    ident VARCHAR(2000),
    guarantee_type_id BIGINT,
    bank_val_proc NUMERIC,
    bank_val_sum NUMERIC,
    sum_from NUMERIC,
    sum_to NUMERIC
);
COMMENT ON TABLE public.scp_prod_guarant_dict IS 'СКП. Гарантии продуктов';

CREATE TABLE IF NOT EXISTS public.scp_prod_comm_dict (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    ident VARCHAR(2000),
    scp_payment_shedule_str VARCHAR(2000),
    scp_comiss_size_str VARCHAR(2000),
    value_comment VARCHAR(2000),
    fare_description VARCHAR(2000),
    is_ho_application SMALLINT,
    com_val_proc NUMERIC,
    is_for_state_program SMALLINT,
    gov_prog_value BIGINT,
    payment_schedule_id BIGINT,
    new_com_val_proc NUMERIC,
    scp_gov_program_id BIGINT REFERENCES public.scp_gov_program_dict(id),
    is_corp_tech_bool SMALLINT,
    is_product_log_bool SMALLINT,
    is_actual_comission SMALLINT,
    is_apk_tech_bool SMALLINT,
    change_comiss_dict_id BIGINT,
    bank_val_sum NUMERIC
);
COMMENT ON TABLE public.scp_prod_comm_dict IS 'СКП. Комиссии продуктов';

CREATE TABLE IF NOT EXISTS public.scp_prod_guar_dict (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    ident VARCHAR(2000),
    scp_comiss_size_str VARCHAR(2000),
    scp_payment_shedule_str VARCHAR(2000),
    value_comment VARCHAR(2000),
    com_val_proc NUMERIC,
    prod_guarant_dict_id BIGINT REFERENCES public.scp_prod_guarant_dict(id),
    gov_prog_value BIGINT,
    payment_schedule_id BIGINT,
    new_com_val_proc NUMERIC,
    scp_gov_program_id BIGINT REFERENCES public.scp_gov_program_dict(id)
);
COMMENT ON TABLE public.scp_prod_guar_dict IS 'СКП. Справочник гарантий продуктов';

CREATE TABLE IF NOT EXISTS public.dict_product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    collateral_id BIGINT,
    guarantee_id BIGINT,
    departure_id BIGINT,
    attr_business_segment BIGINT REFERENCES public.business_segment(id),
    interest_penalties_id BIGINT,
    lending_type_id BIGINT,
    volume_revenue_id BIGINT,
    number_transactions_id BIGINT,
    amount_tender_loan_id BIGINT,
    payment_method_id BIGINT,
    overdraft_limit_id BIGINT,
    max_amount_id BIGINT,
    payment_interest_id BIGINT,
    possibility_delay SMALLINT,
    payment_account SMALLINT,
    early_rep_pos SMALLINT,
    necessity_insurance SMALLINT,
    payment_commission_id BIGINT,
    installment_payment SMALLINT,
    rate_increase_1 SMALLINT,
    id_855918 SMALLINT,
    guarantee_1 SMALLINT,
    min_sum NUMERIC,
    type_of_guarantee_id BIGINT,
    product_relevance SMALLINT,
    comissions_id BIGINT,
    ident VARCHAR(2000),
    valid_decision BIGINT,
    indefinite_period SMALLINT,
    form_issue_id BIGINT,
    part_big_buyer NUMERIC,
    num_months_cashbox NUMERIC,
    num_months_income NUMERIC,
    count_income_month NUMERIC,
    limit_over NUMERIC,
    summ_tranche NUMERIC,
    summ_limit NUMERIC,
    term_limit_credit BIGINT,
    max_sum_credit NUMERIC,
    min_sum_credit NUMERIC,
    forfeight_id BIGINT,
    transfert_rate NUMERIC,
    debt_on_tranche BIGINT,
    type_limit_over_id BIGINT,
    tech_decision_id BIGINT,
    credit_interest_rate NUMERIC,
    dynam_type_id BIGINT,
    form_limit VARCHAR(2000),
    loan_terms BIGINT,
    issue_limit_second VARCHAR(10),
    issue_limit_first VARCHAR(10),
    is_early_repay SMALLINT,
    max_loan_term NUMERIC,
    period_grace VARCHAR(2000),
    card_validity VARCHAR(2000),
    lp_product_code VARCHAR(20),
    dbo_product_code VARCHAR(20),
    cp_product_code VARCHAR(20),
    limit_term VARCHAR(10),
    finstar_product_code VARCHAR(20),
    factoring_product_code VARCHAR(2000),
    is_simplified_fa SMALLINT,
    is_package SMALLINT,
    name_contr_group VARCHAR(2000),
    is_insurance_available SMALLINT,
    is_amd_fill_mandatory SMALLINT,
    is_new_prod_for_ns SMALLINT,
    is_fin_activ_newsub SMALLINT
);
COMMENT ON TABLE public.dict_product IS 'Справочник продуктов';

CREATE TABLE IF NOT EXISTS public.offices_psb (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    parent_org_id BIGINT,
    short_name__ru VARCHAR(2000),
    short_name__en VARCHAR(2000),
    short_name VARCHAR(2000),
    view_id BIGINT,
    main_org BIGINT,
    org_company BIGINT,
    ident VARCHAR(2000),
    office_id VARCHAR(2000),
    office_name VARCHAR(2000),
    office_address VARCHAR(2000),
    office_code VARCHAR(2000),
    office_date_from TIMESTAMP,
    office_date_to TIMESTAMP,
    office_type VARCHAR(2000),
    office_status VARCHAR(2000),
    office_sign_active SMALLINT DEFAULT 1,
    psb_dep_org BIGINT,
    rout_office_id BIGINT REFERENCES public.offices_psb(id),
    lvl_org BIGINT,
    feat_org SMALLINT,
    is_region SMALLINT,
    work_org SMALLINT DEFAULT 1,
    etl_marker_org SMALLINT,
    id_parent_org BIGINT,
    id_depart_org BIGINT,
    id_parent_corr_org BIGINT
);
COMMENT ON TABLE public.offices_psb IS 'Офисы банка';

CREATE TABLE IF NOT EXISTS public.scp_dict_rsc_office (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT,
    ident VARCHAR(2000),
    rsc_office_id BIGINT REFERENCES public.offices_psb(id)
);
COMMENT ON TABLE public.scp_dict_rsc_office IS 'СКП. Офисы РЦБ';

CREATE TABLE IF NOT EXISTS public.yaig_product_dict (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ident VARCHAR(2000)
);
COMMENT ON TABLE public.yaig_product_dict IS 'УАиГ продукт';

CREATE TABLE IF NOT EXISTS public.sys_algorithm (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__en VARCHAR(2000),
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    type_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    org_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL DEFAULT 1,
    amy_ident VARCHAR(2000) NOT NULL,
    amy_frml_text TEXT,
    amy_alg_type_id BIGINT NOT NULL DEFAULT 1,
    amy_base_type_id BIGINT,
    amy_sys_alg_not_replace_null SMALLINT,
    amy_compiled_code TEXT,
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_system SMALLINT DEFAULT 0,
    amy_ver_num BIGINT,
    amy_alg_name VARCHAR(2000),
    amy_use_null_if_src_empty SMALLINT
);
COMMENT ON TABLE public.sys_algorithm IS 'РМ. Алгоритм';

-- =========================================================================
-- LAYER 1: БАЗОВЫЕ СУЩНОСТИ
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.sys_company (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(2000) NOT NULL,
    short_name VARCHAR(2000),
    inn VARCHAR(20),
    type_id BIGINT NOT NULL DEFAULT 1,
    org_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id BIGINT NOT NULL DEFAULT 1,
    name__en VARCHAR(2000),
    name__ru VARCHAR(2000),
    attr_email VARCHAR(2000),
    attr_web_site VARCHAR(2000),
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_system SMALLINT DEFAULT 0,
    attr_reg_country VARCHAR(2000),
    contact_phone VARCHAR(2000),
    main_okved BIGINT,
    business_segment BIGINT REFERENCES public.business_segment(id),
    comp_reg_date TIMESTAMP,
    group_company_link BIGINT,
    company_record_date TIMESTAMP,
    company_registrator VARCHAR(2000),
    company_tax_authority VARCHAR(2000),
    crmd_client_id VARCHAR(2000),
    act_addr_city VARCHAR(2000),
    act_addr_street VARCHAR(2000),
    reg_addr_street VARCHAR(2000),
    reg_addr_city VARCHAR(2000),
    attr_attr_abs VARCHAR(2000),
    tax_authority_reg VARCHAR(2000),
    tax_authority_account VARCHAR(2000),
    customer_type_id BIGINT,
    sign_of_sme SMALLINT,
    date_of_registration TIMESTAMP,
    newly_founded SMALLINT,
    offices_psb_id BIGINT REFERENCES public.offices_psb(id),
    sign_of_bankruptcy SMALLINT,
    stage_of_bankruptcy BIGINT,
    granting_consent SMALLINT,
    date_of_consent TIMESTAMP,
    fo_okved BIGINT,
    busines_segment_id BIGINT,
    d_storage_balance_txt VARCHAR(2000),
    d_storage_finrep_txt VARCHAR(2000),
    is_rko SMALLINT,
    afina_segment_id BIGINT,
    neg_comment VARCHAR(2000),
    neg_status SMALLINT,
    attr_launch_neg_etl SMALLINT
);
COMMENT ON TABLE public.sys_company IS 'Клиенты / Контрагенты';
COMMENT ON COLUMN public.sys_company.inn IS 'ИНН (Sensitive)';
COMMENT ON COLUMN public.sys_company.contact_phone IS 'Телефон (Sensitive)';
COMMENT ON COLUMN public.sys_company.attr_email IS 'Email (Sensitive)';
CREATE INDEX idx_sys_company_inn ON public.sys_company(inn);

CREATE TABLE IF NOT EXISTS public.sys_employee (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(2000) NOT NULL,
    type_id BIGINT NOT NULL DEFAULT 1,
    org_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id BIGINT NOT NULL DEFAULT 1,
    emp_org_id BIGINT NOT NULL DEFAULT 1,
    name__en VARCHAR(2000),
    name__ru VARCHAR(2000),
    first_name VARCHAR(2000),
    second_name VARCHAR(2000),
    sur_name VARCHAR(2000),
    job_pos_id BIGINT,
    email VARCHAR(2000),
    birthday TIMESTAMP,
    phone VARCHAR(100),
    skype VARCHAR(1024),
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_system SMALLINT DEFAULT 0,
    time_zone BIGINT,
    sys_image BIGINT,
    is_locked SMALLINT DEFAULT 0,
    workday_schedule_id BIGINT,
    email_confirmed SMALLINT DEFAULT 0,
    phone_confirmed SMALLINT DEFAULT 0,
    ban_send_notifications SMALLINT DEFAULT 0,
    city_id BIGINT,
    sex_id BIGINT,
    locale_id BIGINT,
    sur_name__ru VARCHAR(2000),
    sur_name__en VARCHAR(2000),
    first_name__ru VARCHAR(2000),
    first_name__en VARCHAR(2000),
    second_name__ru VARCHAR(2000),
    second_name__en VARCHAR(2000),
    ps_office BIGINT REFERENCES public.offices_psb(id),
    adress_ad VARCHAR(2000),
    pers_emp_number VARCHAR(2000),
    inner_emp_phone VARCHAR(2000),
    pers_opt_dmm_link BIGINT
);
COMMENT ON TABLE public.sys_employee IS 'Сотрудники банка';
COMMENT ON COLUMN public.sys_employee.email IS 'Email сотрудника (Sensitive)';
COMMENT ON COLUMN public.sys_employee.phone IS 'Телефон сотрудника (Sensitive)';
CREATE INDEX idx_sys_employee_email ON public.sys_employee(email);

CREATE TABLE IF NOT EXISTS public.sys_object (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(2000) NOT NULL,
    type_id BIGINT NOT NULL DEFAULT 1,
    org_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id BIGINT NOT NULL DEFAULT 1,
    name__en VARCHAR(2000),
    name__ru VARCHAR(2000),
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_system SMALLINT DEFAULT 0
);
COMMENT ON TABLE public.sys_object IS 'Универсальный объект системы';

CREATE TABLE IF NOT EXISTS public.fs_file (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(2000) NOT NULL,
    type_id BIGINT NOT NULL DEFAULT 1,
    org_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id BIGINT NOT NULL DEFAULT 1,
    ff_type_id BIGINT NOT NULL DEFAULT 1,
    ff_storage_id BIGINT NOT NULL DEFAULT 1,
    ff_inner_name VARCHAR(2000) NOT NULL,
    ff_body_size BIGINT NOT NULL DEFAULT 0,
    ff_kind_id BIGINT NOT NULL DEFAULT 1,
    ff_note VARCHAR(2000),
    ff_actual_end_date TIMESTAMP,
    name__en VARCHAR(2000),
    name__ru VARCHAR(2000),
    created_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1,
    last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_system SMALLINT DEFAULT 0,
    ff_parent_object BIGINT,
    ff_is_stored SMALLINT,
    ff_id_881754 TIMESTAMP,
    ff_id_881762 VARCHAR(2000),
    ff_id_881752 TIMESTAMP,
    ff_fs_is_preview_file SMALLINT,
    ff_fs_file_name VARCHAR(2000),
    ff_fv_date_from TIMESTAMP,
    ff_fv_date_to TIMESTAMP,
    ff_body_uuid VARCHAR(2000)
);
COMMENT ON TABLE public.fs_file IS 'Описание файла';

-- =========================================================================
-- LAYER 2: БИЗНЕС-ОБЪЕКТЫ
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.application_obj (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000),
    afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    initiator_id BIGINT,
    emp_id BIGINT REFERENCES public.sys_employee(id),
    processing_steps_id BIGINT,
    temp_cont_turn BIGINT,
    cr_id BIGINT,
    scp_tech_ctredit BIGINT,
    scp_business_segment BIGINT REFERENCES public.business_segment(id),
    client_type_id BIGINT,
    gsl_data_cont_id BIGINT,
    industry_code_id BIGINT,
    scp_product_str VARCHAR(2000),
    is_state_program SMALLINT,
    cred_technology_str VARCHAR(2000),
    is_fin_activ_newsub SMALLINT,
    prelim_gsl_calc_id BIGINT
);
COMMENT ON TABLE public.application_obj IS 'Заявки на кредитование';
CREATE INDEX idx_app_state ON public.application_obj(afp_state_id);
CREATE INDEX idx_app_emp ON public.application_obj(emp_id);

CREATE TABLE IF NOT EXISTS public.credit_contract (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000),
    afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    credit_contract_number VARCHAR(2000),
    loan_term BIGINT,
    credit_amount NUMERIC,
    special_purpose VARCHAR(2000),
    quality_categor VARCHAR(2000),
    financial_position VARCHAR(2000),
    reserve_size NUMERIC,
    link_customer_id BIGINT REFERENCES public.sys_company(id),
    aplication_id BIGINT REFERENCES public.application_obj(id),
    cred_interest_rate NUMERIC,
    sel_curr BIGINT,
    credit_start_date TIMESTAMP,
    credit_end_date TIMESTAMP,
    check_account VARCHAR(2000),
    days_delay_number VARCHAR(2000),
    loan_classified VARCHAR(2000),
    contract_group VARCHAR(2000),
    date_loan_debt NUMERIC,
    prof_judg_id BIGINT,
    contract_type VARCHAR(100),
    credit_product VARCHAR(100),
    applic_ko_kbkp_id BIGINT,
    is_closed SMALLINT,
    pledge_contract_id BIGINT,
    wf_document_id BIGINT,
    cr_status_id BIGINT,
    is_guarantee SMALLINT,
    lname VARCHAR(2000),
    fname VARCHAR(2000),
    mname VARCHAR(2000),
    tabnum VARCHAR(2000),
    sys_employee_id BIGINT REFERENCES public.sys_employee(id),
    subsidy_prog_id BIGINT,
    individ_guarantee SMALLINT,
    offer_ident VARCHAR(2000),
    number_kk VARCHAR(2000),
    protocol_date VARCHAR(2000),
    subsidy_prog_str VARCHAR(2000),
    bank_ident_number VARCHAR(2000),
    tech_link_etl_susp_id BIGINT,
    suspension_na_id BIGINT,
    tech_link_etl_state_id BIGINT,
    appl_documentum_num VARCHAR(2000),
    supplement_tech BIGINT,
    contracttype BIGINT,
    tech_selected_rz_id BIGINT,
    tech_selected_comm VARCHAR(2000),
    tech_selected_meas_id BIGINT,
    yaig_base_code BIGINT,
    hand_suspension SMALLINT,
    duration_over_on_date BIGINT,
    close_contract VARCHAR(2000),
    fa_specialist VARCHAR(2000),
    uid_credit VARCHAR(2000),
    max_loan_amount_ever NUMERIC,
    exite_date TIMESTAMP,
    penalty_rate NUMERIC,
    is_tranche_exist SMALLINT,
    pers_emp_number VARCHAR(2000)
);
COMMENT ON TABLE public.credit_contract IS 'Кредитные договоры';
COMMENT ON COLUMN public.credit_contract.check_account IS 'Расчетный счет (Sensitive)';
COMMENT ON COLUMN public.credit_contract.bank_ident_number IS 'БИК банка';
CREATE INDEX idx_cc_customer ON public.credit_contract(link_customer_id);
CREATE INDEX idx_cc_dates ON public.credit_contract(credit_start_date, credit_end_date);
CREATE INDEX idx_cc_status ON public.credit_contract(status);
CREATE INDEX idx_cc_number ON public.credit_contract(credit_contract_number);

CREATE TABLE IF NOT EXISTS public.count_turnover (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    link_cnt_owner BIGINT REFERENCES public.sys_company(id),
    double_turn_balance SMALLINT,
    finish_period TIMESTAMP,
    count_months BIGINT,
    name VARCHAR(2000),
    name__ru VARCHAR(2000),
    name__en VARCHAR(2000),
    st_period TIMESTAMP,
    account_num_id BIGINT,
    account_source VARCHAR(2000),
    turnover_debit NUMERIC,
    turnover_credit NUMERIC,
    is_check SMALLINT,
    period_st_end VARCHAR(2000),
    parent_link_count BIGINT,
    output_balance_debit NUMERIC,
    output_balance_credit NUMERIC,
    input_balance_debit NUMERIC,
    input_balace_credit NUMERIC,
    link_cred_doc_tur BIGINT,
    link_load_val_id BIGINT,
    link_partic_gr BIGINT,
    is_del SMALLINT,
    correct_type BIGINT,
    tech_manual_vat SMALLINT,
    vat NUMERIC,
    bb_debet_id BIGINT,
    bb_cred_id BIGINT,
    bb_debet_reclass_id BIGINT,
    bb_cred_reclass_id BIGINT,
    out_bal_recl_debt NUMERIC,
    out_bal_recl_cred NUMERIC,
    bb_debet_input_id BIGINT,
    bb_cred_input_id BIGINT
);
COMMENT ON TABLE public.count_turnover IS 'Оборотно-сальдовые ведомости';
CREATE INDEX idx_ct_owner ON public.count_turnover(link_cnt_owner);
CREATE INDEX idx_ct_period ON public.count_turnover(finish_period);

CREATE TABLE IF NOT EXISTS public.afhd_ac_trans_link (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    obj_owner_id BIGINT,
    transaction_id BIGINT,
    source_row_id BIGINT,
    reclass_row_id BIGINT,
    dummy_row_id BIGINT,
    debit_credit_id BIGINT,
    comp_sign_id BIGINT,
    form_inst_id BIGINT,
    form_section_id BIGINT,
    consolidation_obj_id BIGINT,
    statem_trans_id BIGINT,
    multiply_val NUMERIC,
    account_date TIMESTAMP,
    after_amount NUMERIC,
    before_amount NUMERIC,
    is_excepted SMALLINT,
    is_intragroup SMALLINT,
    is_psb_trans SMALLINT,
    copy_source_ac_tr_l_id BIGINT,
    link_turnover BIGINT,
    tbs_item_id BIGINT,
    multiplicator_sign_id BIGINT,
    link_calc_turn_log_id BIGINT,
    okved_activity_id BIGINT,
    vat NUMERIC,
    balance_type_id BIGINT,
    account_num_id BIGINT,
    link_cnt BIGINT,
    cnt_count VARCHAR(2000),
    contragent_name VARCHAR(2000),
    is_clean_apply SMALLINT,
    cnt_turnover_id BIGINT,
    vat_calc NUMERIC,
    link_turnover_reserv BIGINT,
    report_date TIMESTAMP,
    discount NUMERIC,
    cr_id BIGINT
);
COMMENT ON TABLE public.afhd_ac_trans_link IS 'АФХД. Промежуточный тип операции';

CREATE TABLE IF NOT EXISTS public.participant_app (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000),
    name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(),
    type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    org_id BIGINT DEFAULT 1,
    user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(),
    last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1,
    last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    app_obj_id BIGINT,
    borrower_id BIGINT,
    is_current SMALLINT,
    is_check_need SMALLINT,
    part_type_id BIGINT,
    is_permanent_role SMALLINT,
    sec_date_check TIMESTAMP,
    sec_appeal_date TIMESTAMP,
    is_sec_appeal SMALLINT,
    is_antifrod_success SMALLINT,
    is_perm_role_for_head SMALLINT,
    emp_appeal_id BIGINT,
    is_create_check SMALLINT,
    is_add_manual SMALLINT,
    check_role_part_str VARCHAR(2000),
    is_borrower SMALLINT,
    is_related_entity SMALLINT,
    is_affiliate SMALLINT,
    is_pledger SMALLINT,
    is_guarantor SMALLINT,
    return_code_txt TEXT,
    id_siam_str VARCHAR(2000),
    consentbkidate TIMESTAMP,
    is_bch_form_error SMALLINT,
    is_seller SMALLINT,
    scp_link_particip_id BIGINT,
    particip_sec_id BIGINT,
    is_guar_prov_balhold SMALLINT,
    is_state_affilation SMALLINT,
    sec_check_auto_date TIMESTAMP,
    bch_refuse SMALLINT,
    bch_record_link VARCHAR(2000),
    app_obj_person_conn_id BIGINT,
    name__en VARCHAR(2000),
    obj_owner_id BIGINT,
    is_director SMALLINT,
    is_actual_owner SMALLINT,
    is_founder SMALLINT,
    is_legal_person SMALLINT,
    bki_status VARCHAR(2000)
);
COMMENT ON TABLE public.participant_app IS 'Участники сделки';

-- =========================================================================
-- LAYER 3: ЗАЯВКИ СКП / ИУ / КТ / МЛЕР
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.scp_application (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000), afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    initiator_id BIGINT, req_type_id BIGINT, lim_sum NUMERIC,
    loan_terms BIGINT, lim_currency_id BIGINT, gsl_limit NUMERIC,
    credit_logic_id BIGINT, lending_tech_id BIGINT,
    emp_id BIGINT REFERENCES public.sys_employee(id),
    processing_steps_id BIGINT, scp_curr_emp VARCHAR(2000),
    temp_cont_turn BIGINT, risk_zone_id BIGINT, calc_risk_date TIMESTAMP,
    is_active_exp_sec SMALLINT, cr_id BIGINT, scp_appl_type_id BIGINT,
    deleg_region_id BIGINT, scp_hcm_decision_id BIGINT,
    is_active_get_gsl_part SMALLINT, scp_tech_ctredit BIGINT,
    scp_business_segment BIGINT REFERENCES public.business_segment(id),
    is_start_bp_fa SMALLINT, is_tech_ham_task_comp SMALLINT,
    is_collat_exp_launched SMALLINT, is_simplified_fa SMALLINT,
    is_start_bp_request_fa SMALLINT, auto_check_status BIGINT,
    client_type_id BIGINT, gsl_title VARCHAR(2000), other_parts VARCHAR(2000),
    is_without_pledge SMALLINT, is_main_owner SMALLINT, third_parties TEXT,
    decis_level_id BIGINT, ca_decis_level_id BIGINT,
    is_legal_exp_launched SMALLINT, voting_fm_id BIGINT, voting_km_id BIGINT,
    is_legal_exp_restart SMALLINT, scp_gsl_name_str VARCHAR(2000),
    pricing_id BIGINT, price_calc_completed SMALLINT,
    resp_cond_coord BIGINT, curator_head_id BIGINT, is_lspr_level SMALLINT,
    collateral_cont_id BIGINT, clc_grade_id BIGINT,
    scp_arm_manager_id BIGINT, scp_proc_steds_id BIGINT,
    is_auto_sec_errors SMALLINT, is_auto_check_errors SMALLINT,
    is_na_active SMALLINT, reason_refusal_id BIGINT,
    is_form_bch_active SMALLINT, is_bch_validator_on SMALLINT,
    suz_start_page_str VARCHAR(2000), is_active_get_arbitr SMALLINT,
    scp_cheif_cm_id BIGINT, scp_rejection_comment TEXT,
    scp_rejection_client_id BIGINT, ca_rout_office_id BIGINT,
    is_test SMALLINT, client_list_changed SMALLINT, tranche_term NUMERIC,
    is_app_to_cred_depart SMALLINT, scp_type_restruct_id BIGINT,
    is_need_agr_cd_co SMALLINT, is_ca_notif SMALLINT,
    scp_bg_owner_lidm BIGINT, is_check_list_cont_dev SMALLINT,
    is_active_get_dp SMALLINT, scp_bg_current_gr_limit NUMERIC,
    scp_bg_total_prod_limit NUMERIC, is_min_level_changed SMALLINT,
    interm_file_storage BIGINT, is_proj_verif_finished SMALLINT,
    gsl_data_cont_id BIGINT, industry_code_id BIGINT,
    is_cov_bank_garant SMALLINT, scp_product_str VARCHAR(2000),
    is_state_program SMALLINT, cred_technology_str VARCHAR(2000),
    is_not_red_zona_bool SMALLINT, is_not_red_zone BIGINT,
    is_fin_activ_newsub SMALLINT, prelim_gsl_calc_id BIGINT
);
COMMENT ON TABLE public.scp_application IS 'СКП. Заявка';
CREATE INDEX idx_scp_app_initiator ON public.scp_application(initiator_id);

CREATE TABLE IF NOT EXISTS public.ic_application (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000), afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    initiator_id BIGINT, emp_id BIGINT REFERENCES public.sys_employee(id),
    processing_steps_id BIGINT, temp_cont_turn BIGINT, cr_id BIGINT,
    scp_tech_ctredit BIGINT, scp_business_segment BIGINT REFERENCES public.business_segment(id),
    client_type_id BIGINT, gsl_data_cont_id BIGINT,
    scp_arm_manager_id BIGINT, req_type_id BIGINT, credit_logic_id BIGINT,
    gsl_limit NUMERIC, pricing_id BIGINT, scp_gsl_name_str VARCHAR(2000),
    resp_cond_coord BIGINT, curator_head_id BIGINT, resp_cond_coord_str VARCHAR(2000),
    is_auto_creation SMALLINT, industry_code_id BIGINT,
    app_obj_id BIGINT REFERENCES public.application_obj(id),
    deleg_region_id BIGINT, scp_proc_steds_id BIGINT,
    is_directed_to_process SMALLINT, scp_product_str VARCHAR(2000),
    is_state_program SMALLINT, cred_technology_str VARCHAR(2000),
    is_na_active SMALLINT, is_fin_activ_newsub SMALLINT,
    prelim_gsl_calc_id BIGINT, scp_rejection_client_id BIGINT,
    reason_refusal_id BIGINT, is_ic_withdrawn SMALLINT,
    scp_rejection_comment TEXT, is_button_refuse SMALLINT
);
COMMENT ON TABLE public.ic_application IS 'ИУ. Заявка';

CREATE TABLE IF NOT EXISTS public.corp_tech_application (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000), afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    initiator_id BIGINT, emp_id BIGINT REFERENCES public.sys_employee(id),
    processing_steps_id BIGINT, temp_cont_turn BIGINT, cr_id BIGINT,
    scp_tech_ctredit BIGINT, scp_business_segment BIGINT REFERENCES public.business_segment(id),
    client_type_id BIGINT, is_without_pledge SMALLINT,
    lim_currency_id BIGINT, req_type_id BIGINT, credit_logic_id BIGINT,
    gsl_limit NUMERIC, is_main_owner SMALLINT, risk_zone_id BIGINT,
    scp_arm_manager_id BIGINT, loan_terms BIGINT, auto_check_status BIGINT,
    lim_sum NUMERIC, third_parties TEXT, scp_proc_steds_id BIGINT,
    is_active_get_gsl_part SMALLINT, is_na_active SMALLINT,
    deleg_region_id BIGINT, client_list_changed SMALLINT,
    gsl_data_cont_id BIGINT, scp_gsl_name_str VARCHAR(2000),
    ca_rout_office_id BIGINT, is_form_bch_active SMALLINT,
    is_active_exp_sec SMALLINT, scp_hcm_decision_id BIGINT,
    scp_appl_type_id BIGINT, comment_txt TEXT, sec_conclusion_id BIGINT,
    is_bch_validator_on SMALLINT, industry_code_id BIGINT,
    scp_product_str VARCHAR(2000), is_state_program SMALLINT,
    cred_technology_str VARCHAR(2000), is_auto_check_errors SMALLINT,
    scp_type_restruct_id BIGINT, interm_file_storage BIGINT,
    suz_start_page_str VARCHAR(2000), is_legal_exp_launched SMALLINT,
    is_legal_exp_restart SMALLINT, scp_cheif_cm_id BIGINT,
    collat_initiator_id BIGINT, is_return_awp SMALLINT,
    iniciator_emp_id BIGINT, scp_rejection_client_id BIGINT,
    is_app_to_cred_depart SMALLINT, scp_rejection_comment TEXT,
    reason_refusal_id BIGINT, cred_depart_opinion_txt TEXT,
    is_start_bp_fa SMALLINT, is_start_bp_request_fa SMALLINT,
    is_simplified_fa SMALLINT, is_tech_ham_task_comp SMALLINT,
    is_auto_sec_errors SMALLINT, pricing_id BIGINT,
    calc_risk_date TIMESTAMP, collateral_cont_id BIGINT,
    resp_cond_coord BIGINT, is_fin_activ_newsub SMALLINT,
    prelim_gsl_calc_id BIGINT, exp_fa_office_id BIGINT,
    scp_conclusion_comment VARCHAR(2000)
);
COMMENT ON TABLE public.corp_tech_application IS 'КТ. Заявка';

CREATE TABLE IF NOT EXISTS public.mler_application (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000), afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    initiator_id BIGINT, emp_id BIGINT REFERENCES public.sys_employee(id),
    processing_steps_id BIGINT, temp_cont_turn BIGINT, cr_id BIGINT,
    scp_tech_ctredit BIGINT, scp_business_segment BIGINT REFERENCES public.business_segment(id),
    client_type_id BIGINT, lim_sum NUMERIC, gsl_data_cont_id BIGINT,
    scp_cheif_cm_id BIGINT, mler_decis_id BIGINT,
    mler_client_name VARCHAR(2000), is_out_app SMALLINT,
    chief_initiator_id BIGINT, req_type_id BIGINT, execut_admin_id BIGINT,
    mler_signer_id BIGINT, client_section_id BIGINT, project_decis_id BIGINT,
    date_amd_decision TIMESTAMP, num_amd_decision VARCHAR(2000),
    credit_logic_id BIGINT, gsl_limit NUMERIC, loan_terms BIGINT,
    decis_use_limit SMALLINT, signed_risks_date TIMESTAMP,
    deleg_region_id BIGINT, decis_use_limit_text TEXT,
    is_decision_signed SMALLINT, is_decision_approved SMALLINT,
    scp_gsl_name_str VARCHAR(2000), scp_proc_steds_id BIGINT,
    industry_code_id BIGINT, scp_product_str VARCHAR(2000),
    is_state_program SMALLINT, cred_technology_str VARCHAR(2000),
    app_product_id BIGINT, is_fin_activ_newsub SMALLINT,
    prelim_gsl_calc_id BIGINT
);
COMMENT ON TABLE public.mler_application IS 'МЮЭР. Заявка';

-- =========================================================================
-- LAYER 4: ЭКСПЕРТИЗЫ, ПРОЕКТЫ РЕШЕНИЙ, ЗАЛОГИ
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.scp_sec_expertise (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000), afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    emp_id BIGINT REFERENCES public.sys_employee(id),
    sec_end_date TIMESTAMP, expertise_obj_id BIGINT,
    risk_zone_id BIGINT, is_appeal SMALLINT, is_special_inform SMALLINT,
    sec_recall_reason VARCHAR(2000), sec_date_check TIMESTAMP,
    is_ses_withdrawn SMALLINT, reg_resp_emp BIGINT,
    scp_application_id BIGINT, is_region_work SMALLINT,
    start_sec_date TIMESTAMP, dataminer_in_process SMALLINT,
    sf_app_obj_id BIGINT, traf_lights_response_id BIGINT,
    ident VARCHAR(2000), sf_exp_term_date TIMESTAMP, end_date TIMESTAMP,
    reason_revision_str VARCHAR(2000), reason_restart_str VARCHAR(2000),
    reason_cancel_str VARCHAR(2000), sec_exp_copy_id BIGINT,
    deleg_region_id BIGINT, is_company_state_top SMALLINT,
    app_obj_id BIGINT, ct_sec_check_res_id BIGINT,
    psb_office_id BIGINT, csd_expertise_obj_id BIGINT,
    print_form_date TIMESTAMP, deleg_emp_id BIGINT
);
COMMENT ON TABLE public.scp_sec_expertise IS 'СКП. Экспертиза СЭБ';

CREATE TABLE IF NOT EXISTS public.scp_sec_check_res (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    expertise_obj_id BIGINT, sec_date_check TIMESTAMP,
    emp_id BIGINT REFERENCES public.sys_employee(id),
    tech_atr_bool SMALLINT, check_completed SMALLINT,
    is_hide_check_manual SMALLINT, scp_cl_role_str VARCHAR(2000),
    other_comment VARCHAR(2000), settle_accounts_comm VARCHAR(2000),
    family_status_comm VARCHAR(2000), credit_history_comm VARCHAR(2000),
    affil_client_str VARCHAR(2000), aspr_link_zone_id BIGINT,
    aspr_zone_id BIGINT, aspr_affil_res_id BIGINT, aspr_route_id BIGINT,
    bch_mem_res_id BIGINT, aspr_cred_hist_comm VARCHAR(2000),
    affil_check_comm VARCHAR(2000), supp_check_res_id BIGINT,
    sf_family_status_comm TEXT, sf_settle_accounts_comm TEXT,
    sf_credit_history_comm TEXT, sf_other_comment TEXT,
    sf_affil_client_str TEXT, sf_affil_check_comm TEXT
);
COMMENT ON TABLE public.scp_sec_check_res IS 'СКП. Результаты проверок';

CREATE TABLE IF NOT EXISTS public.scp_part_sec_expertise (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    afl_doc_num VARCHAR(2000), afl_doc_data TIMESTAMP,
    afp_state_id BIGINT REFERENCES public.sys_state(id),
    emp_id BIGINT REFERENCES public.sys_employee(id),
    sec_date_check TIMESTAMP, revoke_reason VARCHAR(2000),
    expertise_obj_id BIGINT, deleg_region_id BIGINT,
    risk_zone_id BIGINT, sec_expertise_id BIGINT,
    sec_ch_res_list BIGINT, ses_resp_user_id BIGINT,
    check_completed SMALLINT, ses_conf_user_id BIGINT,
    check_button_vis SMALLINT, repeat_check BIGINT,
    finish_task_date TIMESTAMP, psb_office_id BIGINT,
    sec_check_auto_date TIMESTAMP, ident VARCHAR(2000),
    sf_exp_term_date TIMESTAMP, end_date TIMESTAMP,
    reason_revision_str VARCHAR(2000), reason_restart_str VARCHAR(2000),
    reason_cancel_str VARCHAR(2000), csd_expertise_obj_id BIGINT,
    sf_sec_rs_emp_id BIGINT
);
COMMENT ON TABLE public.scp_part_sec_expertise IS 'СКП. Экспертиза СЭБ участника';

CREATE TABLE IF NOT EXISTS public.scp_collateral_app (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    app_obj_id BIGINT, exp_obj_id BIGINT, out_collateral_id BIGINT,
    collateral_link VARCHAR(2000), coll_appl_type_id BIGINT,
    na_pledge_type_id BIGINT, pledge_addr_str VARCHAR(2000),
    security_quality_id BIGINT, quality_group_id BIGINT,
    liquidity_level_id BIGINT, attr_market_val NUMERIC,
    attr_fair_val NUMERIC, attr_collateral_val NUMERIC,
    collat_obj_name VARCHAR(2000), emp_id BIGINT REFERENCES public.sys_employee(id),
    ca_exp_emp_id BIGINT, cur_upd_appl_id BIGINT,
    parent_collat_app_id BIGINT, collateral_discount NUMERIC,
    discount_rate NUMERIC, appl_state_id BIGINT,
    is_pres_spouse_cons SMALLINT, is_pres_guar_pled SMALLINT,
    necessity_insurance SMALLINT, subs_pledge_id VARCHAR(2000),
    total_struct_share NUMERIC, is_current_concl SMALLINT,
    conclus_txt TEXT, pledge_concl_state_id BIGINT,
    is_export_suz SMALLINT, pledge_conclus_date TIMESTAMP,
    concl_validity_date TIMESTAMP, perform_hr_face_id BIGINT,
    pledge_subject_id BIGINT, collat_common_obj_id BIGINT,
    collat_subj_count BIGINT, scp_arm_chief_id BIGINT,
    cp_arm_manager_id BIGINT, scp_info_comment_txt TEXT,
    scp_info_proj_fin SMALLINT, scp_info_adress_str VARCHAR(2000),
    scp_info_sec_cost NUMERIC, scp_info_type_na_id BIGINT,
    scp_info_cred_summ NUMERIC, scp_info_type_prod_id BIGINT,
    scp_info_pledger_id BIGINT, scp_project_fin_id BIGINT,
    scp_fin_proj_id BIGINT, scp_quest_dec_id BIGINT,
    add_comm_concl_txt TEXT, coll_link_str VARCHAR(2000),
    scp_file_req_timest TIMESTAMP, scp_info_vnd_id BIGINT,
    quest_decis_id BIGINT, testnumber NUMERIC
);
COMMENT ON TABLE public.scp_collateral_app IS 'СКП. Залоговая заявка';

CREATE TABLE IF NOT EXISTS public.scp_decision_quest (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    app_obj_id BIGINT, scp_sublimit_sum NUMERIC,
    scp_sublimit_purpose BIGINT, app_product_id BIGINT,
    scp_sublimit_srok NUMERIC, scp_sublimit_val BIGINT,
    scp_subl_bor BIGINT, annotation TEXT, question_structure TEXT,
    scp_dec_quest_id BIGINT, scp_gov_program_id BIGINT REFERENCES public.scp_gov_program_dict(id),
    source_financing_id BIGINT, credit_purpose_id BIGINT,
    est_credit_limit NUMERIC, is_inactive SMALLINT,
    is_state_program SMALLINT, type_loan_id BIGINT REFERENCES public.type_loan(id),
    is_afhd SMALLINT, rate_type_id BIGINT, product_compound_id BIGINT,
    amdp_parent_product_id BIGINT, scp_state_id BIGINT,
    scp_project_ans_link BIGINT, is_product_recalc SMALLINT,
    ord BIGINT, sys_file_id BIGINT, appr_sum NUMERIC,
    product_compound_str VARCHAR(2000), loan_type_id BIGINT,
    part_excl_ship_debitor BIGINT, attr_business_segment BIGINT REFERENCES public.business_segment(id),
    scp_num_subl BIGINT, sublimit_sum NUMERIC, subl_num VARCHAR(2000),
    is_ca_change_class SMALLINT, credit_report_class BIGINT,
    tech_atr_bool SMALLINT, copy_source_quest_id BIGINT
);
COMMENT ON TABLE public.scp_decision_quest IS 'СКП. Вопросы на принятие решения';

CREATE TABLE IF NOT EXISTS public.scp_project_ans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    req_link_id BIGINT, question_link_id BIGINT,
    voting_km_id BIGINT, voting_fm_id BIGINT,
    draft_decision_id BIGINT, urm_undwrt_decision_id BIGINT,
    decis_level_id BIGINT, doc_num VARCHAR(2000), doc_data TIMESTAMP,
    is_under_3_years_exp SMALLINT, scp_loan_sign_id BIGINT,
    loan_sign_st_ot_id BIGINT, okpd2 VARCHAR(2000),
    curret_limit_gsl NUMERIC, new_limit_gsl NUMERIC,
    current_limit_borow NUMERIC, new_limit_borow NUMERIC,
    set_matrix_limit NUMERIC, real_estate_class_id BIGINT,
    loan_type_id BIGINT, amount_rub NUMERIC, credit_line_term NUMERIC,
    summ_tranche NUMERIC, tranche_term NUMERIC, monthly_contribution NUMERIC,
    payment_delay_months BIGINT, amount_blanc_deal NUMERIC,
    blanc_deal_asmt_result BIGINT, individual_repay_sched TEXT,
    rate_increase_blanc NUMERIC, repayment_type_id BIGINT,
    susp_cond_prev_id BIGINT, curator_head_id BIGINT,
    resp_head_cm_id BIGINT, credit_analyst_id BIGINT,
    is_infinite_vkl SMALLINT, is_blanc_credit SMALLINT,
    exp_limit_credit_rub NUMERIC, refer_empl BIGINT, spec_fa BIGINT,
    attr_market_val NUMERIC, attr_fair_val NUMERIC, product_security NUMERIC,
    attr_collateral_val NUMERIC, collateral_monit BIGINT,
    limit_confirmation BIGINT, amdp_parent_product_id BIGINT,
    scp_state_id BIGINT, rm_ra_decis_level_id BIGINT, voting_rm_id BIGINT,
    plan_deal_date TIMESTAMP, is_active_pj SMALLINT, okved_activity_id BIGINT,
    is_poci_active SMALLINT, mon_col_type_id BIGINT, prod_sec NUMERIC,
    el_individual NUMERIC, clc_grade_id BIGINT, resp_risk_manager_id BIGINT,
    cancel_manage_desic VARCHAR(2000), cancel_manag_desic TEXT,
    undwrit_appl_id BIGINT, is_refresh_state SMALLINT, industry_code_id BIGINT,
    scp_subl_bor BIGINT, client_type_id BIGINT, gsl_comparison VARCHAR(2000),
    clc_zone_id BIGINT, restruct_init_id BIGINT, monit_viol_txt TEXT,
    analys_res_cl_txt TEXT, analys_res_cl_restr_id BIGINT, deal_change_txt TEXT,
    changed_decision_num VARCHAR(2000), deal_change_restr_txt TEXT,
    scp_type_restruct_id BIGINT, min_decis_level_id BIGINT,
    modif_num_deals VARCHAR(2000), scp_matrix_type BIGINT,
    is_need_agr_cd_co SMALLINT, state_id BIGINT, is_old_visual_needed SMALLINT,
    change_initiator_id BIGINT, scp_is_individual SMALLINT,
    lidm_cur_limit NUMERIC, lidm_cur_limit_new NUMERIC,
    scp_bg_owner_lidm BIGINT, scp_chief_ca_id BIGINT,
    total_looped_sum NUMERIC, gsl_compare_txt TEXT,
    limit_confirm_str VARCHAR(2000), proj_city_str VARCHAR(2000),
    is_primary_preparation SMALLINT, req_type_id BIGINT,
    is_cov_bank_garant SMALLINT, memo_deal_log SMALLINT,
    ns_deal_cond_log SMALLINT, confirm_cred_limit_log SMALLINT,
    confirm_csd_log SMALLINT, limit_due_date TIMESTAMP,
    limit_review_date TIMESTAMP, credit_group_id BIGINT,
    raroc_roe NUMERIC, weighted_margin NUMERIC, raroc_perc NUMERIC,
    is_risk_consideration SMALLINT
);
COMMENT ON TABLE public.scp_project_ans IS 'СКП. Проект решения';

-- =========================================================================
-- LAYER 5: ПРОДУКТЫ, ЦЕНЫ, УАиГ
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.scp_amd_product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    app_product_id BIGINT, loan_type_id BIGINT REFERENCES public.type_loan(id),
    scp_sublimit_val BIGINT, scp_general_amount NUMERIC,
    amdp_parent_product_id BIGINT, product_term BIGINT,
    product_limitation BIGINT, product_compound_id BIGINT,
    type_gov_prog_id BIGINT, is_inactive SMALLINT,
    blanc_deal_asmt_result BIGINT, is_blanc_credit SMALLINT,
    monthly_contribution NUMERIC, loan_type_afhd_id BIGINT,
    repayment_type_id BIGINT, rate_increase_blanc NUMERIC,
    amount_blanc_deal NUMERIC, amount_blanc_deal_clt NUMERIC,
    allowed_blanc_amo_prod NUMERIC, is_contract_logic_p SMALLINT,
    draft_dec_id BIGINT, is_oth_bank_guar_psb SMALLINT,
    contr_cont_id BIGINT, is_add_req_bank_guar SMALLINT,
    security_part_id BIGINT, is_requirements_meets SMALLINT,
    is_sdo SMALLINT, comp_type_gov_prog_id BIGINT, clc_grade_id BIGINT,
    exp_limit_credit_rub NUMERIC, el_individual NUMERIC, clc_zone_id BIGINT,
    ident_viol_req VARCHAR(2000), seq_subproduct_numb VARCHAR(2000),
    scp_loan_sign BIGINT, borr_restr_seq_num BIGINT, curr_loan_debt BIGINT,
    amount_loan_debt NUMERIC, product_risk_asses_id BIGINT,
    test_amd_proj_link BIGINT, scp_prod_quest_id BIGINT, amd_proj_link BIGINT,
    prod_term_date TIMESTAMP, scp_loan_sign_id BIGINT, amd_prod_link_id BIGINT,
    cl_group_id BIGINT, question_structure TEXT, is_over_limit SMALLINT
);
COMMENT ON TABLE public.scp_amd_product IS 'СКП. РУМ. Продукт РУМ';

CREATE TABLE IF NOT EXISTS public.product_pricing (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    pricing_card_id BIGINT, owner_object_id BIGINT,
    scp_is_individual SMALLINT, scp_calc_rate_val NUMERIC,
    scp_min_margin_val NUMERIC, offer_margin_over NUMERIC,
    rate_type_id BIGINT, scp_sublimit_srok NUMERIC, scp_sublimit_sum NUMERIC,
    draft_decision_id BIGINT, is_inactive SMALLINT,
    product_pricing_id BIGINT, is_state_program SMALLINT,
    tranche_term NUMERIC, tranche_term_days NUMERIC, g_rate_principal NUMERIC,
    cr_amount NUMERIC, tender_guarantees VARCHAR(2000),
    execution_guarantee VARCHAR(2000), scp_min_insec_margin NUMERIC,
    term_days NUMERIC, pay_reward_cond_id BIGINT,
    amdp_parent_product_id BIGINT, el_individual NUMERIC,
    is_param_calc SMALLINT, cr_limit_guar NUMERIC, clc_grade_id BIGINT,
    pricing_compare_id BIGINT, scp_modif_lim_quest_id BIGINT,
    clc_zone_id BIGINT, scp_sublimit_sum_prev NUMERIC, gsl_limit NUMERIC,
    type_loan_id BIGINT REFERENCES public.type_loan(id),
    app_product_id BIGINT, product_compound_id BIGINT,
    scp_min_margin_from NUMERIC, scp_min_margin NUMERIC,
    min_insec_margin_from NUMERIC, min_insec_margin_to NUMERIC,
    scp_calc_rate_val_from NUMERIC, scp_calc_rate_val_to NUMERIC,
    is_marge_range SMALLINT, scp_min_margin_val_from SMALLINT,
    offer_margin_over_from NUMERIC, offer_margin_over_to NUMERIC,
    fix_spread_value NUMERIC, change_initiator_id BIGINT,
    product_pricing_cast_id BIGINT, is_out_app SMALLINT,
    sublimit_sum NUMERIC, is_umb_surety SMALLINT, cl_group_id BIGINT
);
COMMENT ON TABLE public.product_pricing IS 'СКП. Ценообразование по продукту';

CREATE TABLE IF NOT EXISTS public.prod_change_params (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    product_pricing_id BIGINT, change_param_dict_id BIGINT,
    scp_new_cond VARCHAR(2000), scp_old_cond_val VARCHAR(2000),
    scp_old_cond VARCHAR(2000), scp_new_cond_val VARCHAR(2000),
    value_comment VARCHAR(2000), link_card_obj_id BIGINT,
    com_val_proc NUMERIC, payment_schedule_id BIGINT,
    pay_reward_cond_id BIGINT, sum_pay_type_id BIGINT, comm_date_pay_id BIGINT,
    bank_val_sum NUMERIC, new_bank_val_sum NUMERIC,
    new_pay_reward_cond_id BIGINT, new_com_val_proc NUMERIC,
    scp_comiss_size_str VARCHAR(2000), new_comiss_size_str VARCHAR(2000),
    is_add_manual SMALLINT, is_auto_creation SMALLINT
);
COMMENT ON TABLE public.prod_change_params IS 'СКП. Изменяемые параметры продукта';

CREATE TABLE IF NOT EXISTS public.prod_commissions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    prod_comm_dict_id BIGINT, scp_comiss_size_str VARCHAR(2000),
    scp_payment_shedule_str VARCHAR(2000), com_val_proc NUMERIC,
    value_comment VARCHAR(2000), link_card_obj_id BIGINT,
    is_for_state_program SMALLINT, comm_date_pay_id BIGINT,
    sum_pay_type_id BIGINT, payment_schedule_id BIGINT,
    is_from_pricing SMALLINT, is_add_manual SMALLINT,
    is_current_conds SMALLINT, commission_out_of_dict SMALLINT,
    bank_val_sum NUMERIC
);
COMMENT ON TABLE public.prod_commissions IS 'СКП. Комиссии продукта';

CREATE TABLE IF NOT EXISTS public.prod_guarantees (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    link_card_obj_id BIGINT, prod_guarant_dict_id BIGINT REFERENCES public.scp_prod_guarant_dict(id),
    bank_val_proc NUMERIC, bank_val_sum NUMERIC, guarantee_type_id BIGINT,
    is_from_pricing SMALLINT, is_current_conds SMALLINT
);
COMMENT ON TABLE public.prod_guarantees IS 'СКП. Гарантии продукта';

CREATE TABLE IF NOT EXISTS public.sys_obj_resp (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__en VARCHAR(2000), name__ru VARCHAR(2000), name VARCHAR(2000) NOT NULL,
    create_date TIMESTAMP NOT NULL DEFAULT NOW(), type_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1, org_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL DEFAULT 1, afe_emp_id BIGINT NOT NULL DEFAULT 1,
    afe_obj_id BIGINT NOT NULL DEFAULT 1, afe_subject_id BIGINT NOT NULL DEFAULT 1,
    created_emp_id BIGINT NOT NULL DEFAULT 1, last_modified_user_id BIGINT NOT NULL DEFAULT 1,
    last_modified_emp_id BIGINT NOT NULL DEFAULT 1, last_modified_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_system SMALLINT DEFAULT 0, afe_ext_obj_id BIGINT, afe_resp_comment TEXT,
    afe_short_name VARCHAR(2000), afe_start_stamp TIMESTAMP, afe_end_stamp TIMESTAMP,
    afe_current_resp BIGINT, afe_manage_emp BIGINT
);
COMMENT ON TABLE public.sys_obj_resp IS 'Ответственные сотрудники';

CREATE TABLE IF NOT EXISTS public.scp_dict_product_na (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    ord BIGINT, ident VARCHAR(2000), contract_group VARCHAR(2000),
    credit_product VARCHAR(100), app_product_id BIGINT,
    yaig_product_id BIGINT, contr_group_id BIGINT
);
COMMENT ON TABLE public.scp_dict_product_na IS 'СКП. Продукт из НА';

CREATE TABLE IF NOT EXISTS public.yaig_client_gen_agr (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    yaig_client_princip_id BIGINT, yaig_gen_agr_id BIGINT,
    yaig_gen_agr_sum NUMERIC, yaig_date_close TIMESTAMP,
    yaig_date_open TIMESTAMP, yaig_gen_agr_num VARCHAR(2000),
    yaig_unused_limit NUMERIC, yaig_gen_agr_type_id BIGINT,
    yaig_cur_id BIGINT, yaig_client_link BIGINT, yaig_base_code BIGINT
);
COMMENT ON TABLE public.yaig_client_gen_agr IS 'УАиГ. Генеральное соглашение';

CREATE TABLE IF NOT EXISTS public.yaig_client_guarantee (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name__ru VARCHAR(2000), name__en VARCHAR(2000), name VARCHAR(2000),
    create_date TIMESTAMP DEFAULT NOW(), type_id BIGINT DEFAULT 1,
    status SMALLINT DEFAULT 1, org_id BIGINT DEFAULT 1, user_id BIGINT DEFAULT 1,
    last_modified_date TIMESTAMP DEFAULT NOW(), last_modified_user_id BIGINT DEFAULT 1,
    created_emp_id BIGINT DEFAULT 1, last_modified_emp_id BIGINT DEFAULT 1,
    is_system SMALLINT DEFAULT 0,
    yaig_client_princip_id BIGINT, yaig_product_id BIGINT,
    yaig_guar_summ NUMERIC, yaig_manager_name VARCHAR(2000),
    yaig_risk_group BIGINT, yaig_manager_code BIGINT,
    yaig_quality_categ BIGINT, yaig_guar_type_id BIGINT,
    yaig_prnt_gen_agr_id BIGINT, yaig_cur_id BIGINT,
    yaig_client_link BIGINT, yaig_date_close TIMESTAMP,
    yaig_date_open TIMESTAMP, yaig_guar_num VARCHAR(2000),
    yaig_guarantee_id BIGINT, yaig_sum_commis NUMERIC,
    yaig_manager_code_str VARCHAR(2000), yaig_guar_disclosure TIMESTAMP,
    yaig_guar_payments_bool SMALLINT, yaig_guar_payment BIGINT,
    contr_group_id BIGINT, aggr_protocol_num VARCHAR(2000),
    appl_documentum_num VARCHAR(2000), yaig_base_code BIGINT
);
COMMENT ON TABLE public.yaig_client_guarantee IS 'УАиГ. Гарантия клиента';

-- =========================================================================
-- LAYER 6: MS_* (MultiSelect) таблицы
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.ms_0golbfqyrdq4im6jf6ajivwy9 (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_0n8ohjyx7oszo6a47ca9g0s6f (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_0oc5mpme8nklimjy77sai9gf1 (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_1fd5jp86pabxu9na4knwphvyr (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_333s6j5jn97srp008gyi3zueo (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_39qrctc1n8efr9axiukjssgzl (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_64cm5ded37z58x0fyt5lgvhc7 (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_965j58mgwkpomnuooc29dlq9f (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_9k60rv4p0oaf3c702f2l1gj77 (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_d1oakp9uq175ak3dbhpzbu81d (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_dlggiqkhqj46rhq1lrgryim7c (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_dxsh6488ihf77xmsd43dwby6k (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);
CREATE TABLE IF NOT EXISTS public.ms_e5lum3lbateqhx8wkgtstxdf9 (
    id BIGINT NOT NULL, obj_id BIGINT NOT NULL,
    PRIMARY KEY (id, obj_id)
);